#Application Configuration
server:
  port: 8085
  error:
    include-message: always
    include-binding-errors: always

# To See H2 Console in Browser:
# http://localhost:8081/h2-console
# Enabling H2 Console
spring:
  application:
    name: session-service
  h2:
    console:
      enabled: true
  # ===============================
  # DB
  # ===============================

  datasource:
  url: jdbc:mysql://35.198.55.80:3306/ilanguage_session_fas
  driverClassName: com.mysql.cj.jdbc.Driver
  username: sebtou
  password: Payasito123456*

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: =org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
axon:
  axonserver:
    servers: localhost
  eventhandling:
    processors:
      SessionInfra:
        mode: subscribing
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
eureka:
  client:
    serviceUrl:
      defaultZone: https://ilanguage-registry-service-fas-do7mck57bq-uc.a.run.app/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
