server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: https://ilanguage-registry-service-fas-do7mck57bq-uc.a.run.app/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: subscription-service
          uri: lb://subscription-service
          predicates:
            - Path=/subscriptions/**
        - id: session-service
          uri: lb://session-service
          predicates:
            - Path=/sessions/**
        - id: externaltool-service
          uri: lb://externaltool-service
          predicates:
            - Path=/externaltool/**
        
