#Application Configuration
server:
  port: https://ilanguage-subscription-microservice.azurewebsites.net
  error:
    include-message: always
    include-binding-errors: always
axon:
  axonserver:
    servers: 13.90.21.17
  eventhandling:
    processors:
      SubscriptionInfra:
        mode: subscribing
# To See H2 Console in Browser:
# http://localhost:8081/h2-console
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
  # ===============================
  # DB
  # ===============================

  datasource:
  url: jdbc:mysql://mysqlinstance08.mysql.database.azure.com:3306/Ilanguange-subscripcion-fas
  driverClassName: com.mysql.cj.jdbc.Driver
  username: sebtou
  password: ^z7zc0p090u2sPQa3XH4I#uGCGqCL@Bc5&^^Xvcf4vaK4

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: =org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
