#Application Configuration
server:
  port: https://ilanguage-subscription-microservice.azurewebsites.net
  error:
    include-message: always
    include-binding-errors: always
axon:
  axonserver:
    servers: 13.90.21.17
  eventhandling:
    processors:
      SubscriptionInfra:
        mode: subscribing
# To See H2 Console in Browser:
# http://localhost:8081/h2-console
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
  # ===============================
  # DB
  # ===============================

  datasource:
  url: jdbc:mysql://35.198.55.80:3306/ilanguage-subscription-fas
  driverClassName: com.mysql.cj.jdbc.Driver
  username: sebtou
  password: Payasito123456*

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: =org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
eureka:
  client:
    serviceUrl:
      defaultZone: https://ilanguage-config-server-fas-do7mck57bq-rj.a.run.app
management:
  endpoints:
    web:
      exposure:
        include: "*"
