# HTTP Server
server:
  port: 8888

spring:
  # Spring Cloud Config Server Repository
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Fun-Team-UPC/spring-cloud-config-data.git

  # Spring properties in case you use different profiles
  profiles:
    active: dev