# HTTP Server
server:
  port: 8888

spring:
  # Spring Cloud Config Server Repository
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Fun-Team-UPC/spring-cloud-config-data.git
          searchPaths:
            username: ${GIT_USER}
            password: ${GIT_PASSWORD}
            default-label: "master"
#  # Spring properties in case you use different profiles
#  profiles:
#    active: dev
  security:
      user:
        name: root
        password: s3cr3t